In [1]:
import pandas as pd
import numpy as mp
import os

In [4]:
os.getcwd()

'E:\\4th-Year\\DATA-301\\DATA-301-Directory\\course-project-group_1052\\analysis\\Thomas'

In [5]:
os.chdir('../../')

In [6]:
kidzbop_cens = pd.read_csv('data/raw/KB_censored-lyrics.csv')
kidzbop_cens.head(5)

,ogArtist,songName,badword,count,category,year,isCensored,isPresent,ogLyric,kbLyric
0,Ariana Grande,7 rings,bitch,2,profanity,2019,1,1,Bought matching diamonds for six of my bitches,Bought matching diamonds so they know what thi...
1,Britney Spears,till the world ends,blow,1,alcohol & drugs,2011,1,1,"Baby, let me blow your mind tonight","Baby, come on wave your hands tonight"
2,Britney Spears,till the world ends,blow,2,alcohol & drugs,2011,1,1,"Baby, let me blow your mind tonight","Baby, come on wave your hands tonight"
3,Britney Spears,till the world ends,touch,1,sexual,2011,1,1,"Get you off with the touch, dancing in the dark",Set it off with a track dancing in the dark
4,Elle King,ex's and oh's,high,1,alcohol & drugs,2016,1,1,"I get high, and I love to get low","I get by, and I love to lay low"

## What do we want to change in our dataframe?
1. Remove kbLyric, ogLyric, and songName
2. rename badword to badWord
3. sort by year
4. subsort by artist name alphabetically

In [11]:
df = (
    kidzbop_cens.drop(columns=['songName', 'ogLyric', 'kbLyric'])
      .rename(columns={'badword':'badWord'})
      .sort_values("ogArtist", ascending = True)
      .sort_values("year", ascending = True)
     )
df.head(10)

               ogArtist badWord  count  category  year  isCensored  isPresent
244  Christina Aguilera     sex      1    sexual  2001           1          1
831                 Len     man      1  identity  2001           1          1
832                 LFO     hip      2    sexual  2001           1          1
67              Aaliyah   freak      1    sexual  2002           1          1
126            Baha Men   woman      3  identity  2002           1          1
125            Baha Men   woman      2  identity  2002           1          1
442        Evan & Jaron   crazy      6     other  2002           1          1
441        Evan & Jaron   crazy      4     other  2002           1          1
124            Baha Men   woman      1  identity  2002           1          1
440        Evan & Jaron   crazy      2     other  2002           1          1

In [21]:
def load_and_process(path):
    df1 = pd.read_csv(path)
    
    df2 = (
        df1.drop(columns=['songName', 'ogLyric', 'kbLyric'])
            .rename(columns={'badword':'badWord'})
            .sort_values("ogArtist", ascending = True)
            .sort_values("year", ascending = True)
    )
    return df2

In [22]:
load_and_process('data/raw/KB_censored-lyrics.csv')

,ogArtist,badWord,count,category,year,isCensored,isPresent
244,Christina Aguilera,sex,1,sexual,2001,1,1
831,Len,man,1,identity,2001,1,1
832,LFO,hip,2,sexual,2001,1,1
67,Aaliyah,freak,1,sexual,2002,1,1
126,Baha Men,woman,3,identity,2002,1,1
...,...,...,...,...,...,...,...
386,Ed Sheeran,cigarette,1,alcohol & drugs,2019,1,1
385,Ed Sheeran,bottle,1,alcohol & drugs,2019,1,1
384,Ed Sheeran,bar,3,alcohol & drugs,2019,1,1
382,Ed Sheeran,bar,1,alcohol & drugs,2019,1,1
19,Hilltop Hoods,god,1,other,2019,1,1

In [24]:
from analysis.scripts import project_functions_Tom as pf
pf.load_and_process('data/raw/KB_censored-lyrics.csv')

,ogArtist,badWord,count,category,year,isCensored,isPresent
244,Christina Aguilera,sex,1,sexual,2001,1,1
831,Len,man,1,identity,2001,1,1
832,LFO,hip,2,sexual,2001,1,1
67,Aaliyah,freak,1,sexual,2002,1,1
126,Baha Men,woman,3,identity,2002,1,1
...,...,...,...,...,...,...,...
386,Ed Sheeran,cigarette,1,alcohol & drugs,2019,1,1
385,Ed Sheeran,bottle,1,alcohol & drugs,2019,1,1
384,Ed Sheeran,bar,3,alcohol & drugs,2019,1,1
382,Ed Sheeran,bar,1,alcohol & drugs,2019,1,1
19,Hilltop Hoods,god,1,other,2019,1,1